### PR TITLE
[Consensus] RandomX POW Implementation & Hardfork

### PR DESCRIPTION
**Pull request by akshaynexus**
This PR intends to implement the randomx Algo to zclassic as a hardfork at certain blockheight or blocktime.This implementation uses references from Veil-Project and monero to achive the current implementation.

### CODE REVIEW

**Comment by akshaynexus** [comment]
Note : I havent tested this yet.Will be doing testing later today.

**Comment by akshaynexus** [comment]
Any update here?Has anyone had time for test this pr or shall I close it ?

**Comment by akshaynexus** [comment]
Looks like no one really had time to reply to this,understood,closing

**Comment by heyrhett** [comment]
I'm interested in exploring RandomX as a PoW option for Zclassic

**Comment by mahofmahof** [comment]
> I'm interested in exploring RandomX as a PoW option for Zclassic

It will be nice you had plans about decreasing the block reward too,it can be implemented too
and randomx will make everyone to mine ZCL easier and we will be more decentralised

**Comment by akshaynexus** [comment]
Reducing block reward won't make it more decentralized,just reduces inflation

**Comment by mahofmahof** [comment]
> Reducing block reward won't make it more decentralized,just reduces inflation

but changing algo to randomx it will make it more decentralised, it is a nice algo with easy cpu mining, more people also random peaople will be able to mine.

**Comment by mahofmahof** [comment]
There will be much more miners and we will have more secure network

**Comment by akshaynexus** [comment]
Yeah thats what i opened this pr for,to add randomx algo to zcl,it is compiling on my side ,Need to change a bit but no one has been able to review this pr yet.

**Comment by cryptoprofutonium** [comment]
@akshaynexus Thanks for the hard work. I'll test it and get back to you.

**Comment by akshaynexus** [comment]
@cryptoprofutonium any update on testing?

**Comment by akshaynexus** [comment]
There were some implementation issues,this is fixed and currently works on regtest,waiting for someone to review the pr,its been over a month since i have opened this pr and no one had the time till nwo to review the code.I am assuming no maintainers have the time to review this?

**Comment by akshaynexus** [comment]
Build fails on travis due to 403 forbidden errors,would be nice if someone took the time to review this pr .

**Comment by joshuayabut** [comment]
Holy shit as an idea this is awesome. I will review it tomorrow.

**Comment by t4t-jyabut** [comment]
I can't get the current codebase to run the tests without any failures yet. I'll relook at this once I get the basic tests running clean.

**Comment by joshuayabut** [comment]
I can't get the current codebase to run the tests without any failures yet. I'll relook at this once I get the basic tests running clean.

**Comment by akshaynexus** [comment]
Ok,I checked the tests on master and the same was seen,ie some.tests fail.on master

**Comment by joshuayabut** [comment]
Screenshot from 2020-05-15 16-09-23

I've tried running the RandomX build and am not able to sync up with the current blockchain. I'm assuming there is alot going that needs to be modified before we can implement RandomX. This is on my to-do list but will probably take quite some time to complete.

**Comment by akshaynexus** [comment]
Thats due to         consensus.nRandomXActivationHeight = 690000;

Change that to say 1 million blocks and you can sync mainnet

**Comment by akshaynexus** [comment]
nvm thats my fault of not rebasing on master,will do shortly

**Comment by joshuayabut** [comment]
Ok thanks for all of this... I wish I had some more bandwidth to review at the moment. Would you be able to run tests over regtest for the hardfork block?

**Comment by akshaynexus** [comment]
Could you explain what you mean by that?write tests to test randomx fork or test locally via regtest?i tested it on regtest before submitting the pr and it worked fine.

**Pull request closed without merging**
