### PR TITLE
Deep Reorg Protection

### PR DESCRIPTION
**Pull request by cryptoprofutonium**
This commit implements some basic reorg protection by implementing a rolling 10 block checkpoint

  * Auto-finalize block once they reach a depth of 10 and time of 30mins have elapsed since the block header received time.

  * Introduce a penalty to alternative chains based on the depth of the fork. This makes it harder for an attacker to do reorg before the next block finalization. The node implicitly parks the block if it causes deep reorg. A parked chain will be automatically unparked if it has twice as much PoW accumulated as the main chain since the fork block.

  * Added -maxreorgdepth flag to configure the block finalization depth. Default is 10. Use -1 to disable.

  * Added -finalizationdelay flag to configure the minimum amount of time to wait between block header reception and the block finalization. Unit is seconds, default is 1800 (30mins).

  * Added RPC to park a chain and finalize a block.

  * Added RPC getfinalizedblockhash to get the finalized blockhash.

  * Added RPC tests for reorg protection and also fixed the existing RPC tests.

  * Refactored the code

Signed-off-by: cryptobubbles <cryptobubbles@protonmail.com>

### CODE REVIEW

**Comment by cryptoprofutonium** [comment]
For testing deep reorg protection, follow these steps.
https://medium.com/@prof_crypto/testing-deep-reorg-protection-in-zclassic-ac95c5368bfa

**Comment by matt6412** [comment]
I think it's imperative we extend deprecation policy beyond 16 weeks unless a full time dev can be retained to maintain all wallets and nodes, we still have a qt wallet with a zclassic daemon released as a binary that doesnt even run because of deprecation shutdown and no one has addressed it. @cryptobubbles

**Comment by cryptoprofutonium** [comment]
> I think it's imperative we extend deprecation policy beyond 16 weeks unless a full time dev can be retained to maintain all wallets and nodes, we still have a qt wallet with a zclassic daemon released as a binary that doesnt even run because of deprecation shutdown and no one has addressed it. @cryptobubbles

@matt6412 the commit I just pushed will push a linux release.
which can be directly used within builds for qt wallet and electrum.
I think raising the deprecation hight to an arbitrary high number doesn't make sense.
Hence we reduced it to a 16 week which is the followed release cycle.
The code will most likely get updates before that warning shows up in 14 weeks.

**Comment by cryptoprofutonium** [comment]
Includes #24

**Comment by matt6412** [comment]
> > I think it's imperative we extend deprecation policy beyond 16 weeks unless a full time dev can be retained to maintain all wallets and nodes, we still have a qt wallet with a zclassic daemon released as a binary that doesnt even run because of deprecation shutdown and no one has addressed it. @cryptobubbles
> 
> @matt6412 the commit I just pushed will push a linux release.
> which can be directly used within builds for qt wallet and electrum.
> I think raising the deprecation hight to an arbitrary high number doesn't make sense.
> Hence we reduced it to a 16 week which is the followed release cycle.
> The code will most likely get updates before that warning shows up in 14 weeks.

Well that makes sense re: the zclassic daemon, deprecation height is more of a political debate I suppose, I assume the contributing devs here are , at least for now, going to keep inline with zcash as far as decrecation policy goes, and not follow the path of bitcoin.  I hope the QT binaries get worked on with this new version of zcl next :) good work so far <3

**Comment by matt6412** [comment]
@cryptobubbles do you have a functioning testnet I can join? if so could you share the nodes so i can test this new beast out

**Comment by cryptoprofutonium** [comment]
@matt6412 testnet is active on this branch running v2.0.5 with deep reorg enabled
You can build this branch to run the testnet with the following config
```
gen=1
equihashsolver=tromp
listenonion=0
testnet=1
```

**Comment by cryptoprofutonium** [comment]
The PR is active on testnet and is ready to be merged to Zclassic master for v2.0.5 mainnet.
**Activation height on mainnet: 585318, approximate time: 09-05-2019 00:00 UTC**
**[Consensus::UPGRADE_BUBBLES]. Equihash params changed to 192_7 along with deep reorg protection.**
All nodes must upgrade their client post merge.
Communications to exchanges, mining pools, other people running full node, seed peers etc. to upgrade their nodes, must be carried out post merge.

@heyrhett @hTrap @Skellers21 @matt6412

**Pull request merged**
